Fix ParquetGCSDataSet that had wrongly passed a PosixPath into gcsfs.
The ParquetGCSDataSet dataset in contrib is now passing a string path into gcsfs.GCSFileSystem()'s .invalidate_cache() . ParquetGCSDataSet has been introduced in the recent Kedro 0.15.5 release ( https://github.com/quantumblacklabs/kedro/blob/develop/RELEASE.md ). I suppose no one noticed that invalidate_cache takes a string ( https://github.com/dask/gcsfs/blob/master/gcsfs/core.py#L730 ).

If you try to pass a PosixPath, it will crash with:

'PurePosixPath' object has no attribute 'startswith'

kedro.io.core.DataSetError: Failed while saving data to data set ParquetGCSDataSet

File "/usr/local/anaconda3/envs/v36/lib/python3.6/site-packages/kedro/contrib/io/gcs/parquet_gcs.py", line 159, in invalidate_cache
    self._gcs.invalidate_cache(self._filepath)